### PR TITLE
get icon correctly for MIUI

### PR DESCRIPTION
**Pull request by schspa**
For MIUI, this launcher will got default icon build into apk.
and miui's default is really ugly, and they never update there icon.
this patch get icon from package manager, and will get icon form miui theme manager.

### CODE REVIEW

**Comment by amirzaidi** [comment]
I probably won't add this because I don't want to cause unforeseen bugs, but I can consider putting the proper icons in the Google Icons icon pack

**Comment by schspa** [comment]
How about add a judgment of miui version?  In this way, will only effect miui version.

**Comment by amirzaidi** [comment]
Can you check the latest Telegram build? I implemented it through the CustomIconProvider

**Comment by amirzaidi** [comment]
It causes scaling issues on MIUI so I'm removing it again

**Pull request closed without merging**
