### PR TITLE
Allow hiding icons when not using custom icon pack

### PR DESCRIPTION
**Pull request by pgaskin**
See https://github.com/amirzaidi/Launcher3/issues/472#issuecomment-417861937

I've also built an APK here: https://files.geek1011.net/Android/APKs/Build/

### CODE REVIEW

**Comment by pgaskin** [comment]
@amirzaidi?

**Comment by amirzaidi** [comment]
I will recode this in a proper way when I restart on Pie, for now Oreo is just being maintained with bug fixes because I don't have enough time for it

**Comment by pgaskin** [comment]
Ok, sounds good.

**Comment by khanhvy2703** [comment]
Hi @geek1011 @amirzaidi,
I want to custom this launcher, I will not use app drawer, I only use workspace to show all app.
Could you guide me move all app to workspace by code?
Where I put code to move all app to workspace in first launch app?
Thank you very much.

**Comment by perceival** [comment]
Esteemed Amir,

Is there a chance to get it fixed?

**Comment by amirzaidi** [comment]
@perceival I'm thinking of making a combined codebase on Android 10 from which I can branch Shade and RPL as two release variants. So yes, it will be fixed in the future.

**Pull request closed without merging**
