### PR TITLE
Portuguese update

### PR DESCRIPTION
**Pull request by smarquespt**
Not sure if you accept translation updates but...

### CODE REVIEW

**Comment by amirzaidi** [comment]
Well I could accept it if you would make it so I can see what you changed, instead of removing the msgId everywhere making it impossible to see what was changed

**Comment by smarquespt** [comment]
Sorry about that. Used stringlate for the job and don't know why msgid was removed.
Will do another one with msgid.
Thanks

**Comment by smarquespt** [comment]
It's hard to touch files by hand. Can you consider using an online service like crowdin or weblate? Both provide free hosting for open source projects.

**Comment by amirzaidi** [comment]
Yes I will consider those

**Pull request closed without merging**
