### PR TITLE
Launcher3: fix crash is wallpaper app is not installed

### PR DESCRIPTION
**Pull request by elginsk8r**
Change-Id: Iee5a93e5a932fc0e62ede5f6113091044ea12d09

### CODE REVIEW

**Comment by amirzaidi** [comment]
Can you send me a logcat of it actually crashing? I don't see a reason that the curernt logic should crash

**Comment by elginsk8r** [comment]
intent.setPackage is null and causing a crash. it was experienced when i was using aosp launcher3 and no wallpaper picker package was set. this patch is based on https://github.com/omnirom/android_packages_apps_Launcher3/commit/bf219dba415e841aa8d58ba8a4bf96de279f741a

**Comment by elginsk8r** [comment]
Here is the crash before the patch if wallpaper picker is not installed

06-17 20:30:04.282  5195  5195 E AndroidRuntime: FATAL EXCEPTION: main
06-17 20:30:04.282  5195  5195 E AndroidRuntime: Process: com.android.launcher3, PID: 5195
06-17 20:30:04.282  5195  5195 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SET_WALLPAPER pkg=com.android.documentsui bnds=[105,1560][395,1765] (has extras) }
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4229)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at com.android.launcher3.Launcher.startActivityForResult(Launcher.java:2010)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at com.android.launcher3.Launcher.onClickWallpaperPicker(Launcher.java:2674)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at com.android.launcher3.Launcher$13.onClick(Launcher.java:1399)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22429)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6208)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
06-17 20:30:04.282  5195  5195 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by elginsk8r** [comment]
it's an issue with Launcher in upstream as well. i pushed the patch to their gerrit too https://android-review.googlesource.com/#/c/417450/

**Comment by amirzaidi** [comment]
Yeah it looks like a good fix, I'll apply it for 1.6 if I get to that. For now try installing the Google Wallpapers app, it shouldn't crash with that installed

**Comment by fonix232** [comment]
The main issue here is that Google removed the default wallpaper picker from the Launcher source code. Pulling the Launcher2 wallpaper picker (and possibly updating it in the process to match the UI style?) should be the way to go here, not removing the `android.intent.action.SET_WALLPAPER` intent altogether.

**Pull request closed without merging**
